version: '3'
services:
  mysql:
    image: mysql:latest
    container_name: remix-expenses_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: remix-expenses
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
